"""Static ticker-to-name lookup used for the Portfolio Builder autocomplete.

Covers AEX 25, Nasdaq 100, S&P 500 top-50, and popular ETFs.
Format: "TICKER — Company Name" so users can search by either.
"""

from __future__ import annotations

# {ticker: display_label}
_TICKERS: dict[str, str] = {
    # ── AEX (Amsterdam) ───────────────────────────────────────────────────────
    "ASML.AS":  "ASML Holding",
    "SHELL.AS": "Shell",
    "HEIA.AS":  "Heineken",
    "INGA.AS":  "ING Groep",
    "PHIA.AS":  "Philips",
    "UNA.AS":   "Unilever",
    "NN.AS":    "NN Group",
    "ABN.AS":   "ABN AMRO",
    "RAND.AS":  "Randstad",
    "AKZA.AS":  "Akzo Nobel",
    "WKL.AS":   "Wolters Kluwer",
    "AGN.AS":   "Aegon",
    "KPN.AS":   "KPN",
    "BESI.AS":  "BE Semiconductor",
    "IMCD.AS":  "IMCD Group",
    "ADYEN.AS": "Adyen",
    "AD.AS":    "Ahold Delhaize",
    "MT.AS":    "ArcelorMittal",
    "LIGHT.AS": "Signify",
    "PRX.AS":   "Prosus",
    "OCI.AS":   "OCI",
    "UMG.AS":   "Universal Music Group",
    "VPK.AS":   "Vopak",
    "DSFIR.AS": "DSM-Firmenich",

    # ── Nasdaq 100 ────────────────────────────────────────────────────────────
    "AAPL":  "Apple",
    "MSFT":  "Microsoft",
    "NVDA":  "NVIDIA",
    "AMZN":  "Amazon",
    "META":  "Meta Platforms",
    "TSLA":  "Tesla",
    "GOOGL": "Alphabet (Class A)",
    "GOOG":  "Alphabet (Class C)",
    "AVGO":  "Broadcom",
    "COST":  "Costco",
    "NFLX":  "Netflix",
    "TMUS":  "T-Mobile US",
    "AMD":   "Advanced Micro Devices",
    "PEP":   "PepsiCo",
    "LIN":   "Linde",
    "ADBE":  "Adobe",
    "CSCO":  "Cisco Systems",
    "TXN":   "Texas Instruments",
    "QCOM":  "Qualcomm",
    "AMGN":  "Amgen",
    "ISRG":  "Intuitive Surgical",
    "INTU":  "Intuit",
    "CMCSA": "Comcast",
    "BKNG":  "Booking Holdings",
    "VRTX":  "Vertex Pharmaceuticals",
    "HON":   "Honeywell",
    "AMAT":  "Applied Materials",
    "ADP":   "Automatic Data Processing",
    "SBUX":  "Starbucks",
    "GILD":  "Gilead Sciences",
    "ADI":   "Analog Devices",
    "PANW":  "Palo Alto Networks",
    "LRCX":  "Lam Research",
    "REGN":  "Regeneron Pharmaceuticals",
    "MELI":  "MercadoLibre",
    "MU":    "Micron Technology",
    "KLAC":  "KLA Corporation",
    "CDNS":  "Cadence Design Systems",
    "SNPS":  "Synopsys",
    "MRVL":  "Marvell Technology",
    "CSX":   "CSX",
    "ORLY":  "O'Reilly Automotive",
    "PYPL":  "PayPal",
    "CTAS":  "Cintas",
    "ABNB":  "Airbnb",
    "MAR":   "Marriott International",
    "PCAR":  "PACCAR",
    "ROST":  "Ross Stores",
    "FTNT":  "Fortinet",
    "DXCM":  "Dexcom",
    "MNST":  "Monster Beverage",
    "CPRT":  "Copart",
    "IDXX":  "IDEXX Laboratories",
    "AZN":   "AstraZeneca",
    "MCHP":  "Microchip Technology",
    "NXPI":  "NXP Semiconductors",
    "WDAY":  "Workday",
    "ODFL":  "Old Dominion Freight",
    "CRWD":  "CrowdStrike",
    "FAST":  "Fastenal",
    "KDP":   "Keurig Dr Pepper",
    "BIIB":  "Biogen",
    "DLTR":  "Dollar Tree",
    "EXC":   "Exelon",
    "XEL":   "Xcel Energy",
    "VRSK":  "Verisk Analytics",
    "CTSH":  "Cognizant Technology",
    "GEHC":  "GE HealthCare",
    "ON":    "ON Semiconductor",
    "WBD":   "Warner Bros Discovery",
    "ZS":    "Zscaler",
    "TTWO":  "Take-Two Interactive",
    "FANG":  "Diamondback Energy",
    "CEG":   "Constellation Energy",
    "ROP":   "Roper Technologies",
    "PAYX":  "Paychex",
    "EA":    "Electronic Arts",
    "SPLK":  "Splunk",

    # ── S&P 500 top-50 (non-Nasdaq names) ────────────────────────────────────
    "BRK-B": "Berkshire Hathaway",
    "JPM":   "JPMorgan Chase",
    "V":     "Visa",
    "XOM":   "Exxon Mobil",
    "UNH":   "UnitedHealth Group",
    "MA":    "Mastercard",
    "JNJ":   "Johnson & Johnson",
    "HD":    "Home Depot",
    "PG":    "Procter & Gamble",
    "ABBV":  "AbbVie",
    "BAC":   "Bank of America",
    "CVX":   "Chevron",
    "MRK":   "Merck",
    "LLY":   "Eli Lilly",
    "ORCL":  "Oracle",
    "CRM":   "Salesforce",
    "ACN":   "Accenture",
    "MCD":   "McDonald's",
    "WMT":   "Walmart",
    "KO":    "Coca-Cola",
    "PFE":   "Pfizer",
    "TMO":   "Thermo Fisher Scientific",
    "ABT":   "Abbott Laboratories",
    "INTC":  "Intel",
    "NOW":   "ServiceNow",
    "SPGI":  "S&P Global",
    "UNP":   "Union Pacific",
    "RTX":   "RTX (Raytheon)",
    "GE":    "GE Aerospace",
    "CAT":   "Caterpillar",
    "NEE":   "NextEra Energy",
    "T":     "AT&T",
    "VZ":    "Verizon",
    "IBM":   "IBM",
    "MS":    "Morgan Stanley",
    "GS":    "Goldman Sachs",
    "BLK":   "BlackRock",
    "DE":    "Deere & Company",
    "SCHW":  "Charles Schwab",
    "AXP":   "American Express",
    "CI":    "Cigna",
    "BMY":   "Bristol-Myers Squibb",
    "MO":    "Altria Group",
    "MMM":   "3M",
    "CVS":   "CVS Health",
    "WFC":   "Wells Fargo",
    "C":     "Citigroup",
    "USB":   "U.S. Bancorp",
    "MDT":   "Medtronic",
    "SYK":   "Stryker",
    "ZTS":   "Zoetis",
    "GOOG":  "Alphabet (Class C)",
    "SO":    "Southern Company",
    "DUK":   "Duke Energy",
    "PLD":   "Prologis",
    "AMT":   "American Tower",
    "EQIX":  "Equinix",
    "SHW":   "Sherwin-Williams",
    "APD":   "Air Products",
    "ECL":   "Ecolab",
    "ITW":   "Illinois Tool Works",
    "EMR":   "Emerson Electric",
    "ETN":   "Eaton",
    "CME":   "CME Group",
    "ICE":   "Intercontinental Exchange",
    "MCO":   "Moody's",
    "MSCI":  "MSCI Inc",
    "FIS":   "Fidelity National Information",
    "FISV":  "Fiserv",
    "AON":   "Aon",
    "MMC":   "Marsh & McLennan",
    "PH":    "Parker Hannifin",
    "GD":    "General Dynamics",
    "LMT":   "Lockheed Martin",
    "NOC":   "Northrop Grumman",
    "BA":    "Boeing",
    "TGT":   "Target",
    "LOW":   "Lowe's",
    "SBAC":  "SBA Communications",
    "DG":    "Dollar General",
    "CL":    "Colgate-Palmolive",
    "GIS":   "General Mills",
    "K":     "Kellanova",
    "HCA":   "HCA Healthcare",
    "ISRG":  "Intuitive Surgical",
    "EW":    "Edwards Lifesciences",
    "BSX":   "Boston Scientific",
    "BDX":   "Becton Dickinson",
    "DDOG":  "Datadog",
    "NET":   "Cloudflare",
    "SNOW":  "Snowflake",
    "UBER":  "Uber Technologies",
    "LYFT":  "Lyft",
    "SPOT":  "Spotify",
    "SHOP":  "Shopify",
    "SQ":    "Block (Square)",
    "COIN":  "Coinbase",
    "PLTR":  "Palantir Technologies",
    "RBLX":  "Roblox",
    "U":     "Unity Software",
    "PATH":  "UiPath",
    "MDB":   "MongoDB",
    "GTLB":  "GitLab",
    "HUBS":  "HubSpot",
    "TTD":   "The Trade Desk",
    "APP":   "AppLovin",
    "CELH":  "Celsius Holdings",
    "DUOL":  "Duolingo",

    # ── European blue chips ───────────────────────────────────────────────────
    "SAP":   "SAP SE",
    "LVMH":  "LVMH Moët Hennessy",
    "TTE":   "TotalEnergies",
    "BNP":   "BNP Paribas",
    "SIE":   "Siemens",
    "ALV":   "Allianz",
    "BAYN":  "Bayer",
    "BMW":   "BMW",
    "VOW3":  "Volkswagen",
    "DB1":   "Deutsche Börse",
    "DTE":   "Deutsche Telekom",
    "MUV2":  "Munich Re",
    "NESN":  "Nestlé",
    "NOVN":  "Novartis",
    "ROG":   "Roche",
    "UBSG":  "UBS Group",
    "CSGN":  "Credit Suisse",
    "LONN":  "Lonza Group",
    "ABBN":  "ABB",
    "ZURN":  "Zurich Insurance",
    "MC.PA": "LVMH (Paris)",
    "OR.PA": "L'Oréal",
    "SAN.PA":"Sanofi",
    "BNP.PA":"BNP Paribas (Paris)",
    "AIR.PA":"Airbus",
    "RMS.PA":"Hermès International",
    "CS.PA": "AXA",
    "BVI.PA":"Bureau Veritas",
    "AI.PA": "Air Liquide",

    # ── Popular ETFs ──────────────────────────────────────────────────────────
    "SPY":   "SPDR S&P 500 ETF",
    "QQQ":   "Invesco Nasdaq 100 ETF",
    "VTI":   "Vanguard Total Stock Market ETF",
    "VOO":   "Vanguard S&P 500 ETF",
    "IVV":   "iShares Core S&P 500 ETF",
    "VEA":   "Vanguard FTSE Developed Markets ETF",
    "VWO":   "Vanguard FTSE Emerging Markets ETF",
    "ACWI":  "iShares MSCI ACWI ETF",
    "EEM":   "iShares MSCI Emerging Markets ETF",
    "EFA":   "iShares MSCI EAFE ETF",
    "AGG":   "iShares Core US Aggregate Bond ETF",
    "BND":   "Vanguard Total Bond Market ETF",
    "GLD":   "SPDR Gold Shares",
    "IAU":   "iShares Gold Trust",
    "SLV":   "iShares Silver Trust",
    "USO":   "United States Oil Fund",
    "XLK":   "Technology Select Sector SPDR",
    "XLF":   "Financial Select Sector SPDR",
    "XLV":   "Health Care Select Sector SPDR",
    "XLE":   "Energy Select Sector SPDR",
    "XLI":   "Industrial Select Sector SPDR",
    "XLY":   "Consumer Discretionary Select Sector SPDR",
    "XLP":   "Consumer Staples Select Sector SPDR",
    "XLU":   "Utilities Select Sector SPDR",
    "ARKK":  "ARK Innovation ETF",
    "ARKW":  "ARK Next Generation Internet ETF",
    "SOXX":  "iShares Semiconductor ETF",
    "SMH":   "VanEck Semiconductor ETF",
    "KWEB":  "KraneShares CSI China Internet ETF",
    "TLT":   "iShares 20+ Year Treasury Bond ETF",
    "HYG":   "iShares iBoxx High Yield Corporate Bond ETF",
    "LQD":   "iShares iBoxx Investment Grade Corporate Bond ETF",
    "VXUS":  "Vanguard Total International Stock ETF",
    "VGT":   "Vanguard Information Technology ETF",
    "VHT":   "Vanguard Health Care ETF",
    "VDE":   "Vanguard Energy ETF",
    "VNQ":   "Vanguard Real Estate ETF",
    "PDBC":  "Invesco Optimum Yield Diversified Commodity Strategy ETF",
}


def ticker_options() -> list[str]:
    """Return sorted list of 'TICKER — Company Name' strings for st.selectbox."""
    return sorted(f"{t} — {n}" for t, n in _TICKERS.items())


def extract_ticker(option: str) -> str:
    """Extract ticker symbol from a selectbox option string."""
    return option.split(" — ")[0].strip()
